// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PM_2._0.Models;

#nullable disable

namespace PM_2._0.Migrations
{
    [DbContext(typeof(ProjectManagerContext))]
    [Migration("20260322200420_LinkTeamsWorkersTasksTodos")]
    partial class LinkTeamsWorkersTasksTodos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("PM_2._0.Classes.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("TeamId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("PM_2._0.Classes.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.HasIndex("CurrentTaskId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PM_2._0.Classes.TeamWorker", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("TeamWorkers");
                });

            modelBuilder.Entity("PM_2._0.Classes.Todo", b =>
                {
                    b.Property<int>("TodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TodoId");

                    b.HasIndex("TaskId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("PM_2._0.Classes.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentTodoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerId");

                    b.HasIndex("CurrentTodoId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("PM_2._0.Classes.Task", b =>
                {
                    b.HasOne("PM_2._0.Classes.Team", "Team")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PM_2._0.Classes.Team", b =>
                {
                    b.HasOne("PM_2._0.Classes.Task", "CurrentTask")
                        .WithMany()
                        .HasForeignKey("CurrentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("PM_2._0.Classes.TeamWorker", b =>
                {
                    b.HasOne("PM_2._0.Classes.Team", "Team")
                        .WithMany("Workers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PM_2._0.Classes.Worker", "Worker")
                        .WithMany("Teams")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("PM_2._0.Classes.Todo", b =>
                {
                    b.HasOne("PM_2._0.Classes.Task", "Task")
                        .WithMany("Todos")
                        .HasForeignKey("TaskId");

                    b.HasOne("PM_2._0.Classes.Worker", "Worker")
                        .WithMany("Todos")
                        .HasForeignKey("WorkerId");

                    b.Navigation("Task");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("PM_2._0.Classes.Worker", b =>
                {
                    b.HasOne("PM_2._0.Classes.Todo", "CurrentTodo")
                        .WithMany()
                        .HasForeignKey("CurrentTodoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentTodo");
                });

            modelBuilder.Entity("PM_2._0.Classes.Task", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("PM_2._0.Classes.Team", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("PM_2._0.Classes.Worker", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Todos");
                });
#pragma warning restore 612, 618
        }
    }
}
